### PR TITLE
Reset prop value when its default changes

### PR DESCRIPTION
**Pull request by awseward**
Uncontrollable provides, for every prop it manages, an additional prop to be used for a default value for that prop. For example, `react-widgets`'s `Combobox` uses this with its `value` prop, exposing a `defaultValue` prop. [For more info, see the last paragraph of the README here](https://github.com/jquense/uncontrollable#readme).

Unfortunately, the a prop does not get reset when its default counterpart is changed, so if you are only providing the default value as we do with Combobox in several places, update behavior doesn't quite work in all cases.

This aims to fix that by resetting the value `uncontrollable` will pass along for the prop when the incoming default prop changes.

### CODE REVIEW

**Comment by kespinola** [comment]
@awseward know your managing a bunch of PRs right now, but it may be nice to submit this work to the parent branch too. Thoughts?

**Comment by awseward** [comment]
@ksespinola I'm not sure I understand the question completely.
Do you mean opening up a PR to `jquense/uncontrollable`?
Or do you mean opening this PR to a branch in `procore/uncontrollable` as opposed to master in `procore/uncontrollable`?

**Comment by kespinola** [comment]
`jquense` as a follow up. Then maybe switch back to the parent in the package if its adopted.

**Comment by awseward** [comment]
Absolutely! I would much prefer that to maintaining our own fork of yet another 3rd party node module.

**Comment by thomasm-procore** [comment]
passed testing.

**Comment by remyyounes** [comment]
+1

**Comment by chrisarevir** [comment]
+1

**Comment by mboperator** [comment]
+1

**Pull request merged**
